version: '3.9'

services:
    mockoon:
        build: ./services/mockoon
        profiles:
            - env
        ports:
            - '3000:3000'
        healthcheck:
            test: curl -u 'test:test' localhost:3000/api/token
            interval: 10s
            retries: 60
            start_period: 30s

    master:
        image: locustio/locust:2.20.1
        profiles:
            - test
        env_file:
            - .env
        ports:
            - "8089:8089"
        volumes:
            - ./:/mnt/locust
        command: -f "/mnt/locust/${LOCUST_FILE}" --master -H "${API_ADDRESS}"

    worker:
        image: locustio/locust:2.20.1
        profiles:
            - test
        env_file:
            - .env
        volumes:
            - ./:/mnt/locust
        command: -f "/mnt/locust/${LOCUST_FILE}" --worker --master-host master
