version: '3.9'

services:
  master:
    image: locustio/locust:2.12.1
    env_file:
      - mock_variables.env
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H "http://<LOCAL_IP>:3000" -i <ITERATIONS_BY_USER>

  worker:
    image: locustio/locust:2.12.1
    env_file:
      - mock_variables.env
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
